server:
  port: 8018
  servlet:
    # 大模型对话中文乱码UTF-8编码处理
    encoding:
      enabled: true
      force: true
      charset: UTF-8

spring:
  application:
    name: SAA-Todo-Menu
  output:
    ansi:
      enabled: always
    # spring-alibaba-ai配置
  ai:
    dashscope:
#      base-url: https://dashscope.aliyuncs.com
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
#           qwen-plus
          model: deepseek-v3
      agent:
        options:
          app-id: 66ca0645cbdf4ffb9c14ed442865c21a
