server:
  port: 8002
  servlet:
    # 大模型对话中文乱码UTF-8编码处理
    encoding:
      enabled: true
      force: true
      charset: UTF-8

spring:
  application:
    name: SAA-ollama
  output:
    ansi:
      enabled: always
    # spring-alibaba-ai配置
  ai:
    dashscope:
      api-key: 1111
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          # qwen-plus
          model: qwen3:4b