server:
  port: 8008
  servlet:
    # 大模型对话中文乱码UTF-8编码处理
    encoding:
      enabled: true
      force: true
      charset: UTF-8

spring:
  application:
    name: SAA-Persistent
  output:
    ansi:
      enabled: always
    # spring-alibaba-ai配置
  ai:
    dashscope:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${DASHSCOPE_API_KEY}
#      chat:
#        options:
          # qwen-plus
#          model: deepseek-v3
  data:
    redis:
      host: local-middleware
      port: 6379
      password: toor
      database: 0
      connect-timeout: 3
      timeout: 2